// One-shot removal of the fictional demo content the bootstrap seed created,
// run on every hosted build (idempotent — a clean database is a no-op).
//
// Deletion is precise, not a wipe: scripts/demo-records.json lists the exact
// slugs the seed creates (generated by running the seed into a scratch
// database), so records the team added themselves are never touched. Real
// reference data stays: taxonomy entities and the sports calendar.
//
// A manual snapshot is taken before anything is deleted, so the purge is
// recoverable from Admin → Backups.

import { readFileSync } from "node:fs";
import path from "node:path";
import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

type Manifest = {
  creators: string[]; projects: string[]; organizations: string[];
  formats: string[]; opportunities: string[]; people: string[];
  collections: string[]; savedViews: string[]; sources: string[];
};

const DEMO_USERS = ["editor@440.media", "viewer@440.media"];
const DEMO_ADMIN = "admin@440.media";

async function main() {
  const manifest: Manifest = JSON.parse(
    readFileSync(path.join(process.cwd(), "scripts", "demo-records.json"), "utf8"),
  );

  const bySlug = async (model: "creator" | "project" | "organization" | "format" | "opportunity" | "industryPerson" | "collection", slugs: string[]) =>
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (await (db as any)[model].findMany({ where: { slug: { in: slugs } }, select: { id: true } })).map(
      (r: { id: string }) => r.id,
    ) as string[];

  const [creators, projects, organizations, formats, opportunities, people, collections] = await Promise.all([
    bySlug("creator", manifest.creators),
    bySlug("project", manifest.projects),
    bySlug("organization", manifest.organizations),
    bySlug("format", manifest.formats),
    bySlug("opportunity", manifest.opportunities),
    bySlug("industryPerson", manifest.people),
    bySlug("collection", manifest.collections),
  ]);
  const sources = (
    await db.source.findMany({ where: { title: { in: manifest.sources } }, select: { id: true } })
  ).map((s) => s.id);
  const savedViews = (
    await db.savedView.findMany({ where: { name: { in: manifest.savedViews } }, select: { id: true } })
  ).map((v) => v.id);

  const allIds = [...creators, ...projects, ...organizations, ...formats, ...opportunities, ...people, ...collections];
  const demoUsers = await db.user.findMany({ where: { email: { in: DEMO_USERS } }, select: { id: true } });

  if (allIds.length === 0 && sources.length === 0 && savedViews.length === 0 && demoUsers.length === 0) {
    console.log("remove-demo-data: no demo content found — nothing to do.");
    return;
  }

  console.log(
    `remove-demo-data: purging ${creators.length} talent, ${projects.length} projects, ` +
      `${organizations.length} organizations, ${formats.length} formats, ${opportunities.length} opportunities, ` +
      `${people.length} people, ${collections.length} collections, ${sources.length} sources.`,
  );

  // Safety net first: a full snapshot the team can restore from Admin → Backups.
  try {
    const { createSnapshot } = await import("../src/lib/backup");
    const snap = await createSnapshot("manual", "pre-demo-purge");
    console.log(`Pre-purge snapshot saved (${snap.sizeBytes} bytes).`);
  } catch (e) {
    console.error("Snapshot before purge failed — aborting without deleting anything.", e);
    process.exitCode = 0; // never fail the build; try again next deploy
    return;
  }

  // Rows keyed by targetType/targetId (no FK) that would otherwise go stale.
  await db.knowledgeDigest.deleteMany({ where: { targetId: { in: allIds } } });
  await db.auditLog.deleteMany({ where: { targetId: { in: allIds } } });
  await db.favorite.deleteMany({ where: { targetId: { in: allIds } } });
  await db.recentView.deleteMany({ where: { targetId: { in: allIds } } });
  await db.recordSource.deleteMany({ where: { targetId: { in: allIds } } });

  // The records themselves — relations cascade (links, credits, social
  // profiles, collection items, etc.).
  await db.collection.deleteMany({ where: { id: { in: collections } } });
  await db.savedView.deleteMany({ where: { id: { in: savedViews } } });
  await db.source.deleteMany({ where: { id: { in: sources } } });
  await db.opportunity.deleteMany({ where: { id: { in: opportunities } } });
  await db.format.deleteMany({ where: { id: { in: formats } } });
  await db.creator.deleteMany({ where: { id: { in: creators } } });
  await db.project.deleteMany({ where: { id: { in: projects } } });
  await db.industryPerson.deleteMany({ where: { id: { in: people } } });
  await db.organization.deleteMany({ where: { id: { in: organizations } } });

  // Demo accounts. The demo editor/viewer go; the demo admin goes only when
  // another ADMIN exists (never lock the team out — set ADMIN_EMAIL in Vercel
  // to promote a real account, then the next deploy removes it).
  if (demoUsers.length) {
    await db.auditLog.deleteMany({ where: { userId: { in: demoUsers.map((u) => u.id) } } });
    await db.user.deleteMany({ where: { id: { in: demoUsers.map((u) => u.id) } } });
    console.log(`Removed ${demoUsers.length} demo account(s).`);
  }
  const demoAdmin = await db.user.findUnique({ where: { email: DEMO_ADMIN } });
  if (demoAdmin) {
    const otherAdmins = await db.user.count({ where: { role: "ADMIN", id: { not: demoAdmin.id } } });
    if (otherAdmins > 0) {
      await db.auditLog.deleteMany({ where: { userId: demoAdmin.id } });
      await db.user.delete({ where: { id: demoAdmin.id } });
      console.log(`Removed demo admin ${DEMO_ADMIN} (another admin exists).`);
    } else {
      console.log(
        `Kept ${DEMO_ADMIN} — it is the only ADMIN. Set ADMIN_EMAIL in Vercel to promote a real account; the next deploy will then remove it.`,
      );
    }
  }

  console.log("remove-demo-data: done.");
}

main()
  .catch((e) => {
    // Never fail the build over cleanup — surface and move on.
    console.error("remove-demo-data failed:", e);
  })
  .finally(() => db.$disconnect());
